aws_region: ap-south-1
aws_access_key: *******************
aws_secret_key: *******************
image_id: ami-0bca12658f76ae40c
cidr_block: 10.0.0.0/16
aws_vars:
  - { name: 'subnet1', aws_az: 'ap-south-1a', cidr: '10.0.1.0/24' }
  - { name: 'subnet2', aws_az: 'ap-south-1b', cidr: '10.0.2.0/24' }
